### PR TITLE
[B2C-176] Security enhancement for vulnerable encryption key (EncryptedSharedPreferences)

### PR DESCRIPTION
**Pull request by jwgibanez**
Changes:
- Increase minSdk to support at least level 19 (no risk)
- Increase compileSdk & targetSdk to 31 (no risk)
- Added library "androidx.security:security-crypto:1.1.0-alpha03"
- Updated FlutterSecureStoragePlugin & RSACipher18Implementation classes with v3.3.1+1 as base and adding latest implementation from v5.0.2

### CODE REVIEW

**Comment by thomaslee-u** [comment]
I have no big concern if it references from the current implementation.

But thinking of the release or plan...thinking if it is good to mark down some comments what to remove later ?

since now we use keep the old code for migration (but later on will remove soon).

Guess we will delete that part of code and update this package again ?

**Comment by jwgibanez** [comment]
~~I can add notes and markdown on what to remove for later.~~

I can create a new branch with the removed code for reference later.

**Review by thomaslee-u — APPROVED** [review]

**Comment by jwgibanez** [comment]
Phase 2 changes are found here @thomaslee-u 

https://github.com/yougroupteam/flutter_secure_storage/pull/2

**Comment by jwgibanez** [comment]
Synced this branch to v3.3.5

**Pull request merged**
